### ISSUE TITLE
Assistance

### ISSUE THREAD

**Issue by gib-sec** [cybercdh/kitphishr#1]
Hey, How do I point Kitphishr at a specific URL? Thanks for your help!

**Comment by cybercdh** [comment]
echo https://example.com/index.html | kitphishr

**Comment by harbinc** [comment]
Thanks for the fun tool. Can you search for specific keywords and or specific file names?

**Comment by upxteambr** [comment]
Yes, you can use grep

**Comment by harbinc** [comment]
I have tried using grep and there is no verbose activity. I am not sure if this works or nor,

kitphishr -c 250 -v -d -o kits | grep keyword

grep keyword | kitphishr -c 250 -v -d -o kits

**Comment by harbinc** [comment]
I am not having much luck with grep a file name. Here is the command that I am using. Any suggestions and Thanks for your help.

grep -E 'CHANGELOG.txt|README.txt' | go/bin/kitphishr -c 250 -v -d -o scan

**Comment by cybercdh** [comment]
If you're looking for a specific file within zip files that are returned by kitphishr then perhaps consider using `zipgrep`. 

If you're looking for kitphishr to find those specific file names within the paths it traverses, it's likely the wrong tool of choice.
